ClusterName=aihpc-local
SlurmctldHost=slurm-local

SlurmUser=slurm
SlurmdUser=root

AuthType=auth/munge
CryptoType=crypto/munge

StateSaveLocation=/var/spool/slurmctld
SlurmdSpoolDir=/var/spool/slurmd
SlurmctldPidFile=/run/slurmctld.pid
SlurmdPidFile=/run/slurmd.pid

SlurmctldPort=6817
SlurmdPort=6818

SwitchType=switch/none
MpiDefault=none
ProctrackType=proctrack/pgid
TaskPlugin=task/affinity
JobAcctGatherType=jobacct_gather/linux
ReturnToService=1

SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core

SlurmctldTimeout=120
SlurmdTimeout=300
InactiveLimit=0
KillWait=30
MinJobAge=300

AccountingStorageType=accounting_storage/none
JobCompType=jobcomp/none

NodeName=slurm-local Sockets=1 CoresPerSocket=6 ThreadsPerCore=1 CPUs=6 RealMemory=7939 State=UNKNOWN
PartitionName=debug Nodes=slurm-local Default=YES MaxTime=INFINITE State=UP
